export const yachtsList = [
  {
    id: '1',
    name: 'navigator 215',
    src: '/y1.webp',
    alt: 'navigator 215',
    description: 'The Navigator 215 with her steel hull sets new standards for Megayachts as the most modern yacht in the 65-meter class. The exterior design creates a muscular and sporty modern look with graceful curves and sleek straight lines.',
    gridAreaImg: 'foto1',
    gridAreaDesc: 'desc1',
  },
  {
    id: '2',
    name: 'navigator 160',
    src: '/y2.webp',
    alt: 'navigator 160',
    description: 'The exterior design style is dictated by maximum efficiency and beauty. The exterior design strongly influences the power consumption of the main engines, so our main objective was to seamlessly combine aerodynamics, many solar panels and impressive open decks.',
    gridAreaImg: 'foto2',
    gridAreaDesc: 'desc2',
  },
  {
    id: '3',
    name: 'navigator 130',
    src: '/y3.webp',
    alt: 'navigator 130',
    description: 'The exterior design style is dictated by maximum efficiency and beauty. The exterior design strongly influences the power consumption of the main engines, so our main objective was to seamlessly combine aerodynamics, many solar panels and impressive open decks.',
    gridAreaImg: 'foto3',
    gridAreaDesc: 'desc3',
  },
  {
    id: '4',
    name: 'navigator 100',
    src: '/y1.webp',
    alt: 'navigator 100',
    description: 'The exterior design style is dictated by maximum efficiency and beauty. The exterior design strongly influences the power consumption of the main engines, so our main objective was to seamlessly combine aerodynamics, many solar panels and impressive open decks.',
    gridAreaImg: 'foto4',
    gridAreaDesc: 'desc4',
  },
  {
    id: '5',
    name: 'navigator 80',
    src: '/y2.webp',
    alt: 'navigator 80',
    description: 'The exterior design style is dictated by maximum efficiency and beauty. The exterior design strongly influences the power consumption of the main engines, so our main objective was to seamlessly combine aerodynamics, many solar panels and impressive open decks',
    gridAreaImg: 'foto5',
    gridAreaDesc: 'desc5',
  },
  {
    id: '6',
    name: 'BMW',
    src: '/y3.webp',
    alt: 'BMW',
    description: 'The exterior design style is dictated by maximum efficiency and beauty. The exterior design strongly influences the power consumption of the main engines, so our main objective was to seamlessly combine aerodynamics, many solar panels and impressive open decks',
    gridAreaImg: 'foto6',
    gridAreaDesc: 'desc6',
  },
];